######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 11 18:56:39 2011
######################################################################

TEMPLATE = app
TARGET = QT_RS_Pro_1.0
DESTDIR=../../Bin
DEPENDPATH += . ../SourceCode
INCLUDEPATH += .

# Input
HEADERS += ../SourceCode/mainwindow.h
SOURCES += ../SourceCode/main.cpp\
		  ../SourceCode/mainwindow.cpp
RESOURCES += QtRsPro.qrc
