######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:00:47 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cursor.h
SOURCES += cursor.cpp main.cpp
RESOURCES += cursor.qrc
TRANSLATIONS += cursor_zh.ts
DESTDIR=..\..\Bin
MOC_DIR=..\..\Temp\cursor
RCC_DIR=..\..\Temp\cursor
UI_DIR=..\..\Temp\cursor
OBJECTS_DIR=..\..\Temp\cursor
CONFIG( debug, debug|release ){
DESTDIR=..\..\Bin\Debug
BUILD_NAME = debug
}