######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 26 01:12:36 2011
######################################################################

TEMPLATE = app
TARGET = FindDialog
DESTDIR=../../Bin
DEPENDPATH += . ../SourceCode
INCLUDEPATH += .

# Input
HEADERS += ../SourceCode/finddialog.h
SOURCES += ../SourceCode/finddialog.cpp \
			../SourceCode/main.cpp
