// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `StormNewsDemo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//
#define ICE_STATIC_LIBS
#include <StormNewsDemo.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __Pera__News__NewMsg_name = "NewMsg";

const ::std::string __Pera__PcIdToWsServer__TellClientId_name = "TellClientId";

}
::IceProxy::Ice::Object* ::IceProxy::Pera::upCast(::IceProxy::Pera::News* p) { return p; }

void
::IceProxy::Pera::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Pera::News>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Pera::News;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::Pera::News::NewMsg(const ::std::string& time, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __Pera__News__NewMsg_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::Pera::News* __del = dynamic_cast< ::IceDelegate::Pera::News*>(__delBase.get());
            __del->NewMsg(time, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Pera::News::begin_NewMsg(const ::std::string& time, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Pera__News__NewMsg_name, __del, __cookie);
    try
    {
        __result->__prepare(__Pera__News__NewMsg_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(time);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::Pera::News::end_NewMsg(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Pera__News__NewMsg_name);
}

const ::std::string&
IceProxy::Pera::News::ice_staticId()
{
    return ::Pera::News::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::Pera::News::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::Pera::News);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::Pera::News::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::Pera::News);
}

::IceProxy::Ice::Object*
IceProxy::Pera::News::__newInstance() const
{
    return new News;
}
::IceProxy::Ice::Object* ::IceProxy::Pera::upCast(::IceProxy::Pera::PcIdToWsServer* p) { return p; }

void
::IceProxy::Pera::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Pera::PcIdToWsServer>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Pera::PcIdToWsServer;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::Pera::PcIdToWsServer::TellClientId(const ::std::string& strClientId, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __Pera__PcIdToWsServer__TellClientId_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::Pera::PcIdToWsServer* __del = dynamic_cast< ::IceDelegate::Pera::PcIdToWsServer*>(__delBase.get());
            __del->TellClientId(strClientId, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Pera::PcIdToWsServer::begin_TellClientId(const ::std::string& strClientId, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Pera__PcIdToWsServer__TellClientId_name, __del, __cookie);
    try
    {
        __result->__prepare(__Pera__PcIdToWsServer__TellClientId_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(strClientId);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::Pera::PcIdToWsServer::end_TellClientId(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Pera__PcIdToWsServer__TellClientId_name);
}

const ::std::string&
IceProxy::Pera::PcIdToWsServer::ice_staticId()
{
    return ::Pera::PcIdToWsServer::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::Pera::PcIdToWsServer::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::Pera::PcIdToWsServer);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::Pera::PcIdToWsServer::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::Pera::PcIdToWsServer);
}

::IceProxy::Ice::Object*
IceProxy::Pera::PcIdToWsServer::__newInstance() const
{
    return new PcIdToWsServer;
}

void
IceDelegateM::Pera::News::NewMsg(const ::std::string& time, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Pera__News__NewMsg_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(time);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::Pera::PcIdToWsServer::TellClientId(const ::std::string& strClientId, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Pera__PcIdToWsServer__TellClientId_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(strClientId);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::Pera::News::NewMsg(const ::std::string& time, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::std::string& __p_time, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_time(__p_time)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Pera::News* servant = dynamic_cast< ::Pera::News*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->NewMsg(_m_time, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::std::string& _m_time;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Pera__News__NewMsg_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(time, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::Pera::PcIdToWsServer::TellClientId(const ::std::string& strClientId, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::std::string& __p_strClientId, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_strClientId(__p_strClientId)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Pera::PcIdToWsServer* servant = dynamic_cast< ::Pera::PcIdToWsServer*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->TellClientId(_m_strClientId, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::std::string& _m_strClientId;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Pera__PcIdToWsServer__TellClientId_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(strClientId, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* Pera::upCast(::Pera::News* p) { return p; }

namespace
{
const ::std::string __Pera__News_ids[2] =
{
    "::Ice::Object",
    "::Pera::News"
};

}

bool
Pera::News::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Pera__News_ids, __Pera__News_ids + 2, _s);
}

::std::vector< ::std::string>
Pera::News::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Pera__News_ids[0], &__Pera__News_ids[2]);
}

const ::std::string&
Pera::News::ice_id(const ::Ice::Current&) const
{
    return __Pera__News_ids[1];
}

const ::std::string&
Pera::News::ice_staticId()
{
    return __Pera__News_ids[1];
}

::Ice::DispatchStatus
Pera::News::___NewMsg(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string time;
    __is->read(time);
    __inS.endReadParams();
    NewMsg(time, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Pera__News_all[] =
{
    "NewMsg",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
Pera::News::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Pera__News_all, __Pera__News_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Pera__News_all)
    {
        case 0:
        {
            return ___NewMsg(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Pera::News::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Pera::News::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Pera::__patch(NewsPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Pera::NewsPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Pera::News::ice_staticId(), v);
    }
}

::Ice::Object* Pera::upCast(::Pera::PcIdToWsServer* p) { return p; }

namespace
{
const ::std::string __Pera__PcIdToWsServer_ids[2] =
{
    "::Ice::Object",
    "::Pera::PcIdToWsServer"
};

}

bool
Pera::PcIdToWsServer::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Pera__PcIdToWsServer_ids, __Pera__PcIdToWsServer_ids + 2, _s);
}

::std::vector< ::std::string>
Pera::PcIdToWsServer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Pera__PcIdToWsServer_ids[0], &__Pera__PcIdToWsServer_ids[2]);
}

const ::std::string&
Pera::PcIdToWsServer::ice_id(const ::Ice::Current&) const
{
    return __Pera__PcIdToWsServer_ids[1];
}

const ::std::string&
Pera::PcIdToWsServer::ice_staticId()
{
    return __Pera__PcIdToWsServer_ids[1];
}

::Ice::DispatchStatus
Pera::PcIdToWsServer::___TellClientId(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string strClientId;
    __is->read(strClientId);
    __inS.endReadParams();
    TellClientId(strClientId, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Pera__PcIdToWsServer_all[] =
{
    "TellClientId",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
Pera::PcIdToWsServer::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Pera__PcIdToWsServer_all, __Pera__PcIdToWsServer_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Pera__PcIdToWsServer_all)
    {
        case 0:
        {
            return ___TellClientId(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Pera::PcIdToWsServer::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Pera::PcIdToWsServer::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Pera::__patch(PcIdToWsServerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Pera::PcIdToWsServerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Pera::PcIdToWsServer::ice_staticId(), v);
    }
}
