######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:52:38 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
DESTDIR=..\..\Bin
MOC_DIR=..\..\Temp\hello
RCC_DIR=..\..\Temp\hello
UI_DIR=..\..\Temp\hello
OBJECTS_DIR=..\..\Temp\hello
CONFIG( debug, debug|release ){
DESTDIR=..\..\Bin\Debug
BUILD_NAME = debug
}