######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 19:25:09 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
DESTDIR=..\..\Bin
MOC_DIR=..\..\Temp\dir
RCC_DIR=..\..\Temp\dir
UI_DIR=..\..\Temp\dir
OBJECTS_DIR=..\..\Temp\dir
CONFIG( debug, debug|release ){
DESTDIR=..\..\Bin\Debug
BUILD_NAME = debug
}