######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 26 00:35:33 2011
######################################################################

TEMPLATE = app
TARGET = Slider
DESTDIR=../../Bin
DEPENDPATH += . ../SourceCode
INCLUDEPATH += .

# Input
SOURCES += ../SourceCode/Slider.cpp
