######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 8 20:36:53 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG +=CONSOLE
# Input
SOURCES += main.cpp
