######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 26 20:08:16 2011
######################################################################

TEMPLATE = app
TARGET = StandardDialogs
DESTDIR=../../Bin
DEPENDPATH += . SourceCode
INCLUDEPATH += .

# Input
HEADERS += ../SourceCode/standarddialog.h
SOURCES += ../SourceCode/main.cpp\
			../SourceCode/standarddialog.cpp
