######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 25 11:10:18 2011
######################################################################

TEMPLATE = app
TARGET = Hello
DESTDIR= ../../Bin
DEPENDPATH += . ../SourceCode
INCLUDEPATH += .

# Input
SOURCES += ../SourceCode/main.cpp
