<!DOCTYPE TS><TS>
<context>
    <name>HistogramView</name>
    <message>
        <source>num</source>
        <translation>人数</translation>
    </message>
    <message>
        <source>%1</source>
        <translation></translation>
    </message>
    <message>
        <source>department</source>
        <translation>部门</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <source>Custom View</source>
        <translation>自定义View实现柱状统计图</translation>
    </message>
    <message>
        <source>department</source>
        <translation>部门</translation>
    </message>
    <message>
        <source>male</source>
        <translation>男</translation>
    </message>
    <message>
        <source>female</source>
        <translation>女</translation>
    </message>
    <message>
        <source>retire</source>
        <translation>退休</translation>
    </message>
    <message>
        <source>File</source>
        <translation>文件</translation>
    </message>
    <message>
        <source>Open</source>
        <translation>打开</translation>
    </message>
</context>
</TS>
