######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 25 20:08:06 2011
######################################################################

TEMPLATE = app
TARGET = Dialog
DESTDIR=../../Bin
DEPENDPATH += . ../SourceFile
INCLUDEPATH += .

# Input
HEADERS += ../SourceFile/TestDlg.h
FORMS += ../SourceFile/TestDlg.ui
SOURCES += ../SourceFile/main.cpp\
			../SourceFile/TestDlg.cpp
