######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 26 23:15:04 2011
######################################################################

TEMPLATE = app
TARGET = 
DESTDIR=../../Bin
DEPENDPATH += . ../SourceCode
INCLUDEPATH += .

# Input
HEADERS += ../SourceCode/StandardInput.h
SOURCES += ../SourceCode/main.cpp \
		   ../SourceCode/StandardInput.cpp
