// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `IceCore.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __IceCore_h__
#define __IceCore_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace CoreSpace
{

class CoreBase;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::CoreSpace::CoreBase>&);
::IceProxy::Ice::Object* upCast(::IceProxy::CoreSpace::CoreBase*);

}

}

namespace CoreSpace
{

class CoreBase;
bool operator==(const CoreBase&, const CoreBase&);
bool operator<(const CoreBase&, const CoreBase&);
::Ice::Object* upCast(::CoreSpace::CoreBase*);
typedef ::IceInternal::Handle< ::CoreSpace::CoreBase> CoreBasePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::CoreSpace::CoreBase> CoreBasePrx;
void __patch(CoreBasePtr&, const ::Ice::ObjectPtr&);

}

namespace CoreSpace
{

class Callback_CoreBase_add_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CoreBase_add_Base> Callback_CoreBase_addPtr;

class Callback_CoreBase_sub_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CoreBase_sub_Base> Callback_CoreBase_subPtr;

class Callback_CoreBase_PrintMsg_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CoreBase_PrintMsg_Base> Callback_CoreBase_PrintMsgPtr;

}

namespace IceProxy
{

namespace CoreSpace
{

class CoreBase : virtual public ::IceProxy::Ice::Object
{
public:

    ::Ice::Int add(::Ice::Int a, ::Ice::Int b)
    {
        return add(a, b, 0);
    }
    ::Ice::Int add(::Ice::Int a, ::Ice::Int b, const ::Ice::Context& __ctx)
    {
        return add(a, b, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_add(::Ice::Int a, ::Ice::Int b, const ::IceInternal::Function<void (::Ice::Int)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_add(a, b, 0, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_add(::Ice::Int a, ::Ice::Int b, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_add(a, b, 0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_add(::Ice::Int a, ::Ice::Int b, const ::Ice::Context& ctx, const ::IceInternal::Function<void (::Ice::Int)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_add(a, b, &ctx, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_add(::Ice::Int a, ::Ice::Int b, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_add(a, b, &ctx, ::Ice::newCallback(completed, sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_add(::Ice::Int a, ::Ice::Int b, const ::Ice::Context* ctx, const ::IceInternal::Function<void (::Ice::Int)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception, const ::IceInternal::Function<void (bool)>& sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (::Ice::Int)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::CoreSpace::CoreBasePrx __proxy = ::CoreSpace::CoreBasePrx::uncheckedCast(__result->getProxy());
                ::Ice::Int __ret;
                try
                {
                    __ret = __proxy->end_add(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (::Ice::Int)> _response;
        };
        return begin_add(a, b, ctx, new Cpp11CB(response, exception, sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_add(::Ice::Int a, ::Ice::Int b)
    {
        return begin_add(a, b, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_add(::Ice::Int a, ::Ice::Int b, const ::Ice::Context& __ctx)
    {
        return begin_add(a, b, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_add(::Ice::Int a, ::Ice::Int b, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_add(a, b, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_add(::Ice::Int a, ::Ice::Int b, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_add(a, b, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_add(::Ice::Int a, ::Ice::Int b, const ::CoreSpace::Callback_CoreBase_addPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_add(a, b, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_add(::Ice::Int a, ::Ice::Int b, const ::Ice::Context& __ctx, const ::CoreSpace::Callback_CoreBase_addPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_add(a, b, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_add(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int add(::Ice::Int, ::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_add(::Ice::Int, ::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::Int sub(::Ice::Int a, ::Ice::Int b)
    {
        return sub(a, b, 0);
    }
    ::Ice::Int sub(::Ice::Int a, ::Ice::Int b, const ::Ice::Context& __ctx)
    {
        return sub(a, b, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_sub(::Ice::Int a, ::Ice::Int b, const ::IceInternal::Function<void (::Ice::Int)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_sub(a, b, 0, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_sub(::Ice::Int a, ::Ice::Int b, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_sub(a, b, 0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_sub(::Ice::Int a, ::Ice::Int b, const ::Ice::Context& ctx, const ::IceInternal::Function<void (::Ice::Int)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_sub(a, b, &ctx, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_sub(::Ice::Int a, ::Ice::Int b, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_sub(a, b, &ctx, ::Ice::newCallback(completed, sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_sub(::Ice::Int a, ::Ice::Int b, const ::Ice::Context* ctx, const ::IceInternal::Function<void (::Ice::Int)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception, const ::IceInternal::Function<void (bool)>& sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (::Ice::Int)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::CoreSpace::CoreBasePrx __proxy = ::CoreSpace::CoreBasePrx::uncheckedCast(__result->getProxy());
                ::Ice::Int __ret;
                try
                {
                    __ret = __proxy->end_sub(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (::Ice::Int)> _response;
        };
        return begin_sub(a, b, ctx, new Cpp11CB(response, exception, sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_sub(::Ice::Int a, ::Ice::Int b)
    {
        return begin_sub(a, b, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sub(::Ice::Int a, ::Ice::Int b, const ::Ice::Context& __ctx)
    {
        return begin_sub(a, b, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sub(::Ice::Int a, ::Ice::Int b, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sub(a, b, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sub(::Ice::Int a, ::Ice::Int b, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sub(a, b, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sub(::Ice::Int a, ::Ice::Int b, const ::CoreSpace::Callback_CoreBase_subPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sub(a, b, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sub(::Ice::Int a, ::Ice::Int b, const ::Ice::Context& __ctx, const ::CoreSpace::Callback_CoreBase_subPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sub(a, b, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_sub(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int sub(::Ice::Int, ::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_sub(::Ice::Int, ::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void PrintMsg(const ::std::string& s)
    {
        PrintMsg(s, 0);
    }
    void PrintMsg(const ::std::string& s, const ::Ice::Context& __ctx)
    {
        PrintMsg(s, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_PrintMsg(const ::std::string& s, const ::IceInternal::Function<void ()>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_PrintMsg(s, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(response, exception, sent));
    }
    ::Ice::AsyncResultPtr
    begin_PrintMsg(const ::std::string& s, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_PrintMsg(s, 0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_PrintMsg(const ::std::string& s, const ::Ice::Context& ctx, const ::IceInternal::Function<void ()>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_PrintMsg(s, &ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(response, exception, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_PrintMsg(const ::std::string& s, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_PrintMsg(s, &ctx, ::Ice::newCallback(completed, sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_PrintMsg(const ::std::string& s)
    {
        return begin_PrintMsg(s, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_PrintMsg(const ::std::string& s, const ::Ice::Context& __ctx)
    {
        return begin_PrintMsg(s, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_PrintMsg(const ::std::string& s, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_PrintMsg(s, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_PrintMsg(const ::std::string& s, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_PrintMsg(s, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_PrintMsg(const ::std::string& s, const ::CoreSpace::Callback_CoreBase_PrintMsgPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_PrintMsg(s, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_PrintMsg(const ::std::string& s, const ::Ice::Context& __ctx, const ::CoreSpace::Callback_CoreBase_PrintMsgPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_PrintMsg(s, &__ctx, __del, __cookie);
    }

    void end_PrintMsg(const ::Ice::AsyncResultPtr&);
    
private:

    void PrintMsg(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_PrintMsg(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<CoreBase> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_secure(bool __secure) const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_twoway() const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_oneway() const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_batchOneway() const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_datagram() const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_batchDatagram() const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_compress(bool __compress) const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_timeout(int __timeout) const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<CoreBase> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<CoreBase*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace CoreSpace
{

class CoreBase : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::Ice::Int add(::Ice::Int, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::Ice::Int sub(::Ice::Int, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void PrintMsg(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace CoreSpace
{

class CoreBase : virtual public ::IceDelegate::CoreSpace::CoreBase,
                 virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::Ice::Int add(::Ice::Int, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Ice::Int sub(::Ice::Int, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void PrintMsg(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace CoreSpace
{

class CoreBase : virtual public ::IceDelegate::CoreSpace::CoreBase,
                 virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::Ice::Int add(::Ice::Int, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Ice::Int sub(::Ice::Int, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void PrintMsg(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace CoreSpace
{

class CoreBase : virtual public ::Ice::Object
{
public:

    typedef CoreBasePrx ProxyType;
    typedef CoreBasePtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::Ice::Int add(::Ice::Int, ::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___add(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::Int sub(::Ice::Int, ::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___sub(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void PrintMsg(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___PrintMsg(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const CoreBase& l, const CoreBase& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const CoreBase& l, const CoreBase& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace CoreSpace
{

template<class T>
class CallbackNC_CoreBase_add : public Callback_CoreBase_add_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_CoreBase_add(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CoreSpace::CoreBasePrx __proxy = ::CoreSpace::CoreBasePrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_add(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_CoreBase_addPtr
newCallback_CoreBase_add(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CoreBase_add<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_CoreBase_addPtr
newCallback_CoreBase_add(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CoreBase_add<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_CoreBase_add : public Callback_CoreBase_add_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_CoreBase_add(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CoreSpace::CoreBasePrx __proxy = ::CoreSpace::CoreBasePrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_add(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_CoreBase_addPtr
newCallback_CoreBase_add(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CoreBase_add<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_CoreBase_addPtr
newCallback_CoreBase_add(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CoreBase_add<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_CoreBase_sub : public Callback_CoreBase_sub_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_CoreBase_sub(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CoreSpace::CoreBasePrx __proxy = ::CoreSpace::CoreBasePrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_sub(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_CoreBase_subPtr
newCallback_CoreBase_sub(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CoreBase_sub<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_CoreBase_subPtr
newCallback_CoreBase_sub(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CoreBase_sub<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_CoreBase_sub : public Callback_CoreBase_sub_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_CoreBase_sub(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CoreSpace::CoreBasePrx __proxy = ::CoreSpace::CoreBasePrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_sub(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_CoreBase_subPtr
newCallback_CoreBase_sub(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CoreBase_sub<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_CoreBase_subPtr
newCallback_CoreBase_sub(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CoreBase_sub<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_CoreBase_PrintMsg : public Callback_CoreBase_PrintMsg_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_CoreBase_PrintMsg(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_CoreBase_PrintMsgPtr
newCallback_CoreBase_PrintMsg(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CoreBase_PrintMsg<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_CoreBase_PrintMsgPtr
newCallback_CoreBase_PrintMsg(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CoreBase_PrintMsg<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_CoreBase_PrintMsgPtr
newCallback_CoreBase_PrintMsg(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CoreBase_PrintMsg<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_CoreBase_PrintMsgPtr
newCallback_CoreBase_PrintMsg(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CoreBase_PrintMsg<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_CoreBase_PrintMsg : public Callback_CoreBase_PrintMsg_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_CoreBase_PrintMsg(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_CoreBase_PrintMsgPtr
newCallback_CoreBase_PrintMsg(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CoreBase_PrintMsg<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_CoreBase_PrintMsgPtr
newCallback_CoreBase_PrintMsg(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CoreBase_PrintMsg<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_CoreBase_PrintMsgPtr
newCallback_CoreBase_PrintMsg(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CoreBase_PrintMsg<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_CoreBase_PrintMsgPtr
newCallback_CoreBase_PrintMsg(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CoreBase_PrintMsg<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
